#!/bin/sh

export PATH=/Users/larry/bin:/usr/local/bin:/bin:/usr/bin

mvn package -DskipTests
if [ $? ]; then
  TARGET_DIR=target
  if [ ! -d $TARGET_DIR ]; then
    exit 1
  fi
  
  export PROJECT_BASE=jmsperf
  export TARGET=${TARGET_DIR}/${PROJECT_BASE}

  rm -rf $TARGET && mkdir $TARGET
  
  if [ $? ]; then
    tar xvzf ${TARGET}*.tar.gz --strip-components=1 -C ${TARGET}
  fi
  
  cp ${TARGET}*.tar.gz '/Users/larry/Google Drive/dist/jmsperf'
  exit $?
fi
